import type { Mission } from "./kinds.ts";
import { classifyKind, excerptOf, missionId } from "./kinds.ts";

type Seed = Omit<Mission, "id" | "kind" | "excerpt" | "live" | "language"> & {
  kind?: Mission["kind"];
  language?: string;
};

const RAW: Seed[] = [
  {
    owner: "vitejs",
    repo: "vite",
    number: 23221,
    title:
      "Conditional dynamic imports share one __vitePreload deps array, dropping CSS/preloads for one branch",
    body: "When two dynamic import() calls are used in mutually-exclusive branches and get wrapped by Vite's __vitePreload helper, minification merges the two __vitePreload(...) calls into a single call. The first argument correctly becomes a ternary selecting the right import target, but the second argument (the deps array) does not — it keeps only one branch's deps. In production one branch renders completely unstyled, silently.",
    url: "https://github.com/vitejs/vite/issues/23221",
    labels: ["p3-minor-bug"],
    comments: 4,
    updatedAt: "2026-08-28T15:10:21Z",
    createdAt: "2026-08-10T06:46:24Z",
    isPr: false,
    author: "EduardZaydler",
  },
  {
    owner: "vitejs",
    repo: "vite",
    number: 23392,
    title:
      "vite.config change during an in-flight config restart is silently dropped",
    body: "When vite.config.ts changes, the dev server restarts. If the config file changes again while that restart is still in flight, the second change is silently dropped: server.restart() returns the in-flight promise instead of queueing a follow-up. After git checkout between branches the server stays on the old config until a human touches the file.",
    url: "https://github.com/vitejs/vite/issues/23392",
    labels: [],
    comments: 1,
    updatedAt: "2026-08-28T10:34:58Z",
    createdAt: "2026-08-28T08:05:25Z",
    isPr: false,
    author: "silentoplayz",
  },
  {
    owner: "vitejs",
    repo: "vite",
    number: 23143,
    title: "`server.close()` in JavaScript API hangs forever",
    body: "From Vite 8.1.4 onward, server.close() can hang forever and never resolve. Using the Vite JavaScript API in Vitest leads to tests timing-out. Introduced in 8.1.4; 8.1.3 is fine.",
    url: "https://github.com/vitejs/vite/issues/23143",
    labels: ["p3-minor-bug", "feat: ssr"],
    comments: 6,
    updatedAt: "2026-08-26T06:44:04Z",
    createdAt: "2026-08-03T12:08:24Z",
    isPr: false,
    author: "nicomouss",
  },
  {
    owner: "vitejs",
    repo: "vite",
    number: 23374,
    title:
      "A single failed sass-embedded compiler spawn permanently breaks all scss compilation until server restart",
    body: "When sass-embedded is used, one transient failure to spawn its compiler child process permanently breaks all scss compilation for the lifetime of the dev server. initAsyncCompiler() resolves before spawn settles, and makeScssWorker caches the dead compiler forever.",
    url: "https://github.com/vitejs/vite/issues/23374",
    labels: [],
    comments: 0,
    updatedAt: "2026-08-26T08:26:09Z",
    createdAt: "2026-08-26T08:26:09Z",
    isPr: false,
    author: "lopno",
  },
  {
    owner: "vitejs",
    repo: "vite",
    number: 23377,
    title: "Imported worker missing from Vite build manifest",
    body: "Vite handles imported workers and they show up in the build output, but the worker is not included in the Vite build manifest. Frameworks like SvelteKit use the manifest to collect assets for service-worker caching.",
    url: "https://github.com/vitejs/vite/issues/23377",
    labels: ["pending triage"],
    comments: 1,
    updatedAt: "2026-08-27T07:03:39Z",
    createdAt: "2026-08-26T12:42:22Z",
    isPr: false,
    author: "teemingc",
  },
  {
    owner: "TanStack",
    repo: "query",
    number: 11320,
    title: "Server-side gcTime schedules a GC timer that pins the whole SSR async context",
    body: "On the server updateGcTime falls back to Infinity, so no GC timer is scheduled. As soon as a query passes an explicit finite gcTime, scheduleGc() sets a real setTimeout during SSR. A Node timer captures the async context — the work store, the Request, the HTML and the RSC payload — for the whole gcTime. One useQuery({ gcTime: 24h }) in a root provider left replicas growing to the memory limit.",
    url: "https://github.com/TanStack/query/issues/11320",
    labels: [],
    comments: 0,
    updatedAt: "2026-08-28T06:30:40Z",
    createdAt: "2026-08-28T06:30:40Z",
    isPr: false,
    author: "AdzerKI",
  },
  {
    owner: "TanStack",
    repo: "query",
    number: 11327,
    title: "Falsy query errors disable retryOnMount when throwOnError returns false",
    body: "When a query rejects with a falsy value such as undefined, it does not retry on remount even though retryOnMount is true. ensurePreventErrorBoundaryRetry checks the truthiness of query.state.error, so the throwOnError callback is skipped and retryOnMount is incorrectly disabled.",
    url: "https://github.com/TanStack/query/issues/11327",
    labels: [],
    comments: 0,
    updatedAt: "2026-08-29T11:39:38Z",
    createdAt: "2026-08-29T11:35:45Z",
    isPr: false,
    author: "jeonghoon11",
  },
  {
    owner: "TanStack",
    repo: "query",
    number: 11272,
    title: "useMutationState does not update when filters change (react-query)",
    body: "useMutationState() ignores changes to filters. The result is only recomputed when the mutation cache notifies, so after a filter change the array keeps showing the old filters' results until something unrelated touches the cache.",
    url: "https://github.com/TanStack/query/issues/11272",
    labels: [],
    comments: 0,
    updatedAt: "2026-08-24T13:48:06Z",
    createdAt: "2026-08-24T13:48:06Z",
    isPr: false,
    author: "alex-js-ltd",
  },
  {
    owner: "TanStack",
    repo: "query",
    number: 10145,
    title:
      "HydrationBoundary ignores server-prefetched query when a parent useQuery with same key renders first",
    body: "If a useQuery is rendered before a HydrationBoundary, hydrations for that key are skipped even though the useQuery would not have fetched. Child useSuspenseQuery then fires during SSR despite a prefetch.",
    url: "https://github.com/TanStack/query/issues/10145",
    labels: [],
    comments: 4,
    updatedAt: "2026-08-27T18:57:18Z",
    createdAt: "2026-02-17T22:37:49Z",
    isPr: false,
    author: "ColemanDunn",
  },
  {
    owner: "TanStack",
    repo: "router",
    number: 8195,
    title:
      "SSR build emits two mutually-importing router chunks; every route 500s",
    body: "In a TanStack Start + Nitro SSR build, rolldown emits two common chunks that import each other. Whichever chunk evaluates first sees the other's bindings uninitialised. vite build exits 0. The failure only appears when the built server handles its first request. There is no circular import in the source.",
    url: "https://github.com/TanStack/router/issues/8195",
    labels: [],
    comments: 1,
    updatedAt: "2026-08-30T16:43:05Z",
    createdAt: "2026-08-30T15:31:14Z",
    isPr: false,
    author: "Rjpearso95",
  },
  {
    owner: "TanStack",
    repo: "router",
    number: 7913,
    title: "Start: page route returns 500 when Accept excludes HTML",
    body: "createStartHandler refuses to render a page route when the request's Accept header does not allow HTML, and reports that refusal as 500. A failed content negotiation is a client-side condition, so this should be 406 Not Acceptable.",
    url: "https://github.com/TanStack/router/issues/7913",
    labels: [],
    comments: 3,
    updatedAt: "2026-08-30T09:52:14Z",
    createdAt: "2026-07-28T06:12:48Z",
    isPr: false,
    author: "ollipa",
  },
  {
    owner: "TanStack",
    repo: "router",
    number: 7363,
    title:
      "TanStack Start server functions should return 404 when requested with an invalid ID, currently 500",
    body: "When a server function is requested at an old ID that no longer exists, the framework returns a 500. In production this triggers alerts when BingBot hits cached server-fn routes after a deploy. Any other missing resource would be a 404.",
    url: "https://github.com/TanStack/router/issues/7363",
    labels: [],
    comments: 1,
    updatedAt: "2026-08-21T18:02:26Z",
    createdAt: "2026-05-07T21:19:41Z",
    isPr: false,
    author: "neverstew",
  },
  {
    owner: "TanStack",
    repo: "router",
    number: 8062,
    title:
      "start-compiler-plugin: hotUpdate crashes with TypeError under vite experimental.bundledDev",
    body: "The hotUpdate hook reads this.environment.name unconditionally. Under Vite experimental.bundledDev, Rolldown invokes hotUpdate without an environment, throwing TypeError. The rebuild fails and the dev server serves stale output on every subsequent edit until restart.",
    url: "https://github.com/TanStack/router/issues/8062",
    labels: ["needs-upstream-fix"],
    comments: 1,
    updatedAt: "2026-08-26T23:43:52Z",
    createdAt: "2026-08-13T15:41:39Z",
    isPr: false,
    author: "TIMTOMTOP",
  },
  {
    owner: "TanStack",
    repo: "router",
    number: 8180,
    title:
      "SSR-enabled beforeLoad on root with ssr: false causes Suspense hydration error",
    body: "When using SSR with tanstack start and a route that has a beforeLoad, a router change-of-state triggers a useSyncExternalStore update. Since useSyncExternalStore is always synchronous, it ignores startTransition and invalidates the Suspense boundary of SSR hydration.",
    url: "https://github.com/TanStack/router/issues/8180",
    labels: [],
    comments: 1,
    updatedAt: "2026-08-28T12:12:47Z",
    createdAt: "2026-08-27T19:20:15Z",
    isPr: false,
    author: "fionamatthews-wk",
  },
  {
    owner: "tailwindlabs",
    repo: "tailwindcss",
    number: 20435,
    title:
      'Upgrade codemod rewrites variant="outline" to "outline-solid" inside conditional expressions',
    body: "@tailwindcss/upgrade rewrites variant=\"outline\" to variant=\"outline-solid\" when a conditional expression sits between variant and the string literal. These are React prop values, not class names, so the rewrite silently breaks them. PR #18922 fixed the direct forms; any conditional between variant and the literal still defeats the guard.",
    url: "https://github.com/tailwindlabs/tailwindcss/issues/20435",
    labels: [],
    comments: 0,
    updatedAt: "2026-08-27T22:13:09Z",
    createdAt: "2026-08-27T22:13:09Z",
    isPr: false,
    author: "carlos-cubas",
  },
  {
    owner: "tailwindlabs",
    repo: "tailwindcss",
    number: 20433,
    title:
      "Optimizer warns on Angular's ::ng-deep — the :deep/:slotted/:global filter doesn't cover it",
    body: "optimizeCss already filters Lightning CSS warnings for Vue and Svelte deep selectors, but Angular's ::ng-deep isn't in the list. The message reads 'ng-deep' is not recognized, so the pattern's leading quote never matches because the character before deep is a hyphen.",
    url: "https://github.com/tailwindlabs/tailwindcss/issues/20433",
    labels: [],
    comments: 1,
    updatedAt: "2026-08-26T15:41:53Z",
    createdAt: "2026-08-26T15:37:42Z",
    isPr: false,
    author: "weilinzung",
  },
  {
    owner: "tailwindlabs",
    repo: "tailwindcss",
    number: 20426,
    title:
      "@tailwindcss/vite discards resolve.conditions when resolving CSS @import, but honours them for JS",
    body: "The CSS resolver overwrites conditions with a hardcoded list, so any custom condition set via resolve.conditions is silently dropped for CSS @import while continuing to work for JS. In a monorepo the app renders components from src/ while scanning dist/ for class candidates.",
    url: "https://github.com/tailwindlabs/tailwindcss/issues/20426",
    labels: [],
    comments: 1,
    updatedAt: "2026-08-22T12:23:47Z",
    createdAt: "2026-08-20T22:49:14Z",
    isPr: false,
    author: "jeffberry",
  },
  {
    owner: "tailwindlabs",
    repo: "tailwindcss",
    number: 19722,
    title:
      "[v4] Custom named --spacing-* values shadow leading-none (e.g. --spacing-none: 0 causes line-height: 0)",
    body: "When defining a custom named spacing value --spacing-none: 0 in @theme, the leading-none utility outputs line-height: 0 instead of the expected line-height: 1. The --spacing fallback is needed for numeric values like leading-6, but named values create unintended collisions.",
    url: "https://github.com/tailwindlabs/tailwindcss/issues/19722",
    labels: [],
    comments: 4,
    updatedAt: "2026-08-08T02:43:49Z",
    createdAt: "2026-02-25T06:28:11Z",
    isPr: false,
    author: "nayukata",
  },
  {
    owner: "vitejs",
    repo: "vite",
    number: 23132,
    title:
      "fix(module-runner): don't cache invoke timeout as module result (fix #23131)",
    body: "Open PR. Fixes module-runner caching an invoke timeout as if it were a successful module result.",
    url: "https://github.com/vitejs/vite/pull/23132",
    labels: [],
    comments: 1,
    updatedAt: "2026-08-30T07:59:58Z",
    createdAt: "2026-08-02T08:16:03Z",
    isPr: true,
    author: "nitine",
  },
  {
    owner: "vitejs",
    repo: "vite",
    number: 23360,
    title: "fix(ssr): throw on missing named exports in inlined modules",
    body: "Open PR. SSR currently swallows missing named exports in inlined modules instead of throwing, which hides real breakage until runtime.",
    url: "https://github.com/vitejs/vite/pull/23360",
    labels: [],
    comments: 5,
    updatedAt: "2026-08-28T06:48:08Z",
    createdAt: "2026-08-25T10:25:11Z",
    isPr: true,
    author: "bun-unsafe",
  },
  {
    owner: "TanStack",
    repo: "query",
    number: 11328,
    title: "fix(react-query): retry queries with falsy errors on mount",
    body: "Open PR for #11327. Checks whether the query is in the error state instead of checking the truthiness of the error value, so retryOnMount works for falsy errors.",
    url: "https://github.com/TanStack/query/pull/11328",
    labels: [],
    comments: 1,
    updatedAt: "2026-08-29T11:42:39Z",
    createdAt: "2026-08-29T11:37:35Z",
    isPr: true,
    author: "jeonghoon11",
  },
  {
    owner: "TanStack",
    repo: "query",
    number: 11329,
    title: "fix(react-query): recompute useMutationState when the filters change",
    body: "Open PR for #11272. Recomputes useMutationState when filters change even if the mutation cache has not notified.",
    url: "https://github.com/TanStack/query/pull/11329",
    labels: [],
    comments: 1,
    updatedAt: "2026-08-29T13:36:22Z",
    createdAt: "2026-08-29T13:34:01Z",
    isPr: true,
    author: "MahathirMohammadShuvo",
  },
  {
    owner: "vitejs",
    repo: "vite",
    number: 23401,
    title: "fix(deps): watch asset files in linked optimized dependencies",
    body: "Open PR. Linked optimized dependencies currently miss asset-file watches, so edits to those assets do not invalidate the optimizer.",
    url: "https://github.com/vitejs/vite/pull/23401",
    labels: [],
    comments: 0,
    updatedAt: "2026-08-30T17:01:46Z",
    createdAt: "2026-08-30T16:48:18Z",
    isPr: true,
    author: "gilangabdian",
  },
  {
    owner: "vitejs",
    repo: "vite",
    number: 23151,
    title: "Deploy maintained historical versions of the Chinese documentation",
    body: "New maintainers of the Chinese documentation want historical version branches (stable-5.x, stable-6.x, stable-7.x) deployed to v5/v6/v7.cn.vite.dev. Translation side is ready; needs Vite team deployment config.",
    url: "https://github.com/vitejs/vite/issues/23151",
    labels: ["documentation"],
    comments: 4,
    updatedAt: "2026-08-26T02:39:57Z",
    createdAt: "2026-08-04T04:16:57Z",
    isPr: false,
    author: "dogledogle",
  },
];

export const SEED_MISSIONS: Mission[] = RAW.map((item) => ({
  ...item,
  id: missionId(item.owner, item.repo, item.number),
  kind: item.kind ?? classifyKind(item),
  excerpt: excerptOf(item.body),
  language: item.language ?? "TypeScript",
  live: false,
}));

export function findSeed(
  owner: string,
  repo: string,
  number: number,
): Mission | undefined {
  return SEED_MISSIONS.find(
    (m) =>
      m.owner.toLowerCase() === owner.toLowerCase() &&
      m.repo.toLowerCase() === repo.toLowerCase() &&
      m.number === number,
  );
}
