/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FateRouteImport } from './routes/fate'
import { Route as ListRouteImport } from './routes/list'
import { Route as LogRouteImport } from './routes/log'
import { Route as ApiUsageRouteImport } from './routes/api/usage'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthGithubRouteImport } from './routes/api/auth/github'
import { Route as ROwnerRepoRouteImport } from './routes/r.$owner.$repo'
import { Route as MOwnerRepoNumberRouteImport } from './routes/m.$owner.$repo.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FateRoute = FateRouteImport.update({
  id: '/fate',
  path: '/fate',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageRoute = ApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/api/auth/github',
  path: '/api/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ROwnerRepoRoute = ROwnerRepoRouteImport.update({
  id: '/r/$owner/$repo',
  path: '/r/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const MOwnerRepoNumberRoute = MOwnerRepoNumberRouteImport.update({
  id: '/m/$owner/$repo/$number',
  path: '/m/$owner/$repo/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fate': typeof FateRoute
  '/list': typeof ListRoute
  '/log': typeof LogRoute
  '/api/usage': typeof ApiUsageRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/r/$owner/$repo': typeof ROwnerRepoRoute
  '/m/$owner/$repo/$number': typeof MOwnerRepoNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fate': typeof FateRoute
  '/list': typeof ListRoute
  '/log': typeof LogRoute
  '/api/usage': typeof ApiUsageRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/r/$owner/$repo': typeof ROwnerRepoRoute
  '/m/$owner/$repo/$number': typeof MOwnerRepoNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fate': typeof FateRoute
  '/list': typeof ListRoute
  '/log': typeof LogRoute
  '/api/usage': typeof ApiUsageRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/r/$owner/$repo': typeof ROwnerRepoRoute
  '/m/$owner/$repo/$number': typeof MOwnerRepoNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fate'
    | '/list'
    | '/log'
    | '/api/usage'
    | '/api/auth/callback'
    | '/api/auth/github'
    | '/r/$owner/$repo'
    | '/m/$owner/$repo/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fate'
    | '/list'
    | '/log'
    | '/api/usage'
    | '/api/auth/callback'
    | '/api/auth/github'
    | '/r/$owner/$repo'
    | '/m/$owner/$repo/$number'
  id:
    | '__root__'
    | '/'
    | '/fate'
    | '/list'
    | '/log'
    | '/api/usage'
    | '/api/auth/callback'
    | '/api/auth/github'
    | '/r/$owner/$repo'
    | '/m/$owner/$repo/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FateRoute: typeof FateRoute
  ListRoute: typeof ListRoute
  LogRoute: typeof LogRoute
  ApiUsageRoute: typeof ApiUsageRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthGithubRoute: typeof ApiAuthGithubRoute
  ROwnerRepoRoute: typeof ROwnerRepoRoute
  MOwnerRepoNumberRoute: typeof MOwnerRepoNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fate': {
      id: '/fate'
      path: '/fate'
      fullPath: '/fate'
      preLoaderRoute: typeof FateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage': {
      id: '/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof ApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/api/auth/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$owner/$repo': {
      id: '/r/$owner/$repo'
      path: '/r/$owner/$repo'
      fullPath: '/r/$owner/$repo'
      preLoaderRoute: typeof ROwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$owner/$repo/$number': {
      id: '/m/$owner/$repo/$number'
      path: '/m/$owner/$repo/$number'
      fullPath: '/m/$owner/$repo/$number'
      preLoaderRoute: typeof MOwnerRepoNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FateRoute: FateRoute,
  ListRoute: ListRoute,
  LogRoute: LogRoute,
  ApiUsageRoute: ApiUsageRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthGithubRoute: ApiAuthGithubRoute,
  ROwnerRepoRoute: ROwnerRepoRoute,
  MOwnerRepoNumberRoute: MOwnerRepoNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
